apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app-frontend
  namespace: aks-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: aks-app-frontend

  template:
    metadata:
      labels:
        app: aks-app-frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/thakur-rohit-21/aks-app-frontend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10