apiVersion: v1
kind: Service
metadata:
  name: aks-backend
  namespace: aks-aap
spec:
  type: ClusterIP

  selector:
    app: aks-backend

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP