apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aks-app
type: Opaque
stringData:
  POSTGRES_DB: aksdb
  POSTGRES_USER: aksuser
  POSTGRES_PASSWORD: "ChangeMeStrongPassword123!"